-- AlterTable
ALTER TABLE `bid` ADD COLUMN `claims` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `is_mastermiles` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `is_mentoria` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `member_since` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `recommendations` INTEGER NOT NULL DEFAULT 0;
